/* ==========================================================================
   The Getaway Pinball Arcade — Tailwind Play CDN configuration
   Must be loaded AFTER the Tailwind CDN <script> tag in index.html so the
   global `tailwind` object already exists when this file runs.
   ========================================================================== */

tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c6c6c7",
        "on-surface": "#e5e2e1",
        "inverse-primary": "#c00015",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c8c6c5",
        "primary": "#ffb4ac",
        "surface-container": "#201f1f",
        "surface-container-highest": "#353534",
        "secondary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#1a1c1c",
        "surface-bright": "#3a3939",
        "on-tertiary-container": "#fdfaf9",
        "outline-variant": "#5d3f3c",
        "surface-container-low": "#1c1b1b",
        "error": "#ffb4ac",
        "secondary-container": "#454747",
        "on-secondary-container": "#b4b5b5",
        "on-primary": "#690006",
        "inverse-surface": "#e5e2e1",
        "outline": "#ae8883",
        "error-container": "#93000a",
        "on-primary-fixed": "#410002",
        "tertiary": "#c8c6c5",
        "surface-dim": "#131313",
        "tertiary-container": "#747373",
        "primary-fixed-dim": "#ffb4ac",
        "on-error": "#690005",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "background": "#131313",
        "primary-container": "#e31b23",
        "tertiary-fixed": "#e5e2e1",
        "on-tertiary": "#313030",
        "primary-fixed": "#ffdad6",
        "on-tertiary-fixed": "#1c1b1b",
        "on-surface-variant": "#e7bdb8",
        "on-primary-fixed-variant": "#93000d",
        "on-primary-container": "#fff9f8",
        "inverse-on-surface": "#313030",
        "on-secondary": "#2f3131",
        "on-secondary-fixed-variant": "#454747",
        "surface-tint": "#ffb4ac",
        "surface-container-high": "#2a2a2a",
        "surface": "#131313",
        "secondary": "#c6c6c7",
        "on-tertiary-fixed-variant": "#474746",
        "on-background": "#e5e2e1",
        "accent-red": "#e31b23",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "16px",
        base: "4px",
        xs: "8px",
        md: "24px",
        xl: "64px",
        "margin-desktop": "48px",
        gutter: "20px",
        lg: "40px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        headline: ["Anybody"],
        display: ["Anybody"],
        body: ["Anybody"],
        label: ["Anybody"],
        "body-lg": ["Anybody"],
        "body-md": ["Anybody"],
        "display-xl": ["Anybody"],
        "headline-lg": ["Anybody"],
        "headline-lg-mobile": ["Anybody"],
        "headline-md": ["Anybody"],
        "label-bold": ["Anybody"],
        "label-sm": ["Anybody"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-xl": [
          "80px",
          { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "900" },
        ],
        "headline-lg": [
          "48px",
          { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-md": ["24px", { lineHeight: "28px", fontWeight: "700" }],
        "label-bold": ["14px", { lineHeight: "16px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
      },
    },
  },
};
